
#### How to use Python numpy.where() Method

numpy-like boolean array
https://www.journaldev.com/37898/python-numpy-where?utm_source=browser&utm_medium=rss_notification&utm_id=130675.16730106265

In [1]:
import numpy as np
 
a = np.arange(10)
print(a[a <= 2]) # Will only capture elements <= 2 and ignore others

[0 1 2]


In [2]:
#  Replace Elements with numpy.where()
import numpy as np
 
# Random initialization of a (2D array)
a = np.random.randn(2, 3)
print(a)
 
# b will be all elements of a whenever the condition holds true (i.e only positive elements)
# Otherwise, set it as 0
b = np.where(a > 0, a, 0)
 
print(b)

[[-0.19057982  1.72793407  0.4639849 ]
 [-0.13266475  0.13398985 -0.85124968]]
[[0.         1.72793407 0.4639849 ]
 [0.         0.13398985 0.        ]]


In [3]:
# Using numpy.where() with only a condition

import random
import numpy as np
 
a = np.random.randn(2, 3)
b = np.where(a > 0)
print(b)


(array([0, 0, 1], dtype=int64), array([1, 2, 2], dtype=int64))


In [4]:
# np.asarray.nonzero()
import numpy as np
 
a = np.arange(10)
 
b = np.where(a < 5, a, a * 10)
 
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [5]:
# Broadcasting with numpy.where()

import numpy as np
 
a = np.arange(12).reshape(3, 4)
 
b = np.arange(4).reshape(1, 4)
 
print(a)
print(b)
 
# Broadcasts (a < 5, a, and b * 10)
# of shape (3, 4), (3, 4) and (1, 4)
c = np.where(a < 5, a, b * 10)
 
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4 10 20 30]
 [ 0 10 20 30]]
