
#### How to use Python numpy.where() Method

numpy-like boolean array
https://www.journaldev.com/37898/python-numpy-where?utm_source=browser&utm_medium=rss_notification&utm_id=130675.16730106265

In [1]:
import numpy as np
 
a = np.arange(10)
print(a[a <= 2]) # Will only capture elements <= 2 and ignore others

[0 1 2]


a의 요소값은 어떠한 규칙성이 없으며 b는 정규분포에 따라 행렬의 원소값을 초기화함 

In [2]:
import numpy as np
 
a = np.empty([3, 3])
print(a)
 
b = np.random.randn(3,3)
print(b)

[[0.22786117 0.20858094 0.41315306]
 [0.5437308  1.81619708 0.55612416]
 [0.6154272  0.35306349 0.30553576]]
[[-0.95302129 -1.30047552  0.67290631]
 [ 0.02332209  0.86505198 -2.22343846]
 [-0.76928855  0.20081056 -0.69768889]]


In [3]:
import numpy as np
 
x = np.array([1., 2., 3., 4.])
 
print(x) # output: [1. 2. 3. 4.]
print(type(x)) # output: <'numpy.ndarray'>
print(x.shape) # output: (4,)
print(np.ndim(x)) # output: 1
 
y = np.array([
    [1., 2., 3., 4.],
    [9., 8., 7., 5.]
])
 
print(y.shape) # output: (2, 4)
print(np.ndim(y)) # output: 2

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
(4,)
1
(2, 4)
2


In [4]:
# 원소 접근 
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
print(x[0]) # output: [1 2 3]
print(x[0][0]) # output: 1
print(x[0][0] == x[0,0]) # output: True
 
for r in x:
    print(r)
# output:
# [1 2 3]
# [4 5 6]

[1 2 3]
1
True
[1 2 3]
[4 5 6]


In [5]:
a = np.array([10,20,30])
b = np.array([1,2,3])
 
print(a+b) # output: [11 22 33]
print(a-b) # output: [ 9 18 27]
print(a*b) # output: [10 40 90]
print(a/b) # output: [10. 10. 10.]

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [2]:
#  Replace Elements with numpy.where()
import numpy as np
 
# Random initialization of a (2D array)
a = np.random.randn(2, 3)
print(a)
 
# b will be all elements of a whenever the condition holds true (i.e only positive elements)
# Otherwise, set it as 0
b = np.where(a > 0, a, 0)
 
print(b)

[[-0.19057982  1.72793407  0.4639849 ]
 [-0.13266475  0.13398985 -0.85124968]]
[[0.         1.72793407 0.4639849 ]
 [0.         0.13398985 0.        ]]


In [3]:
# Using numpy.where() with only a condition

import random
import numpy as np
 
a = np.random.randn(2, 3)
b = np.where(a > 0)
print(b)


(array([0, 0, 1], dtype=int64), array([1, 2, 2], dtype=int64))


In [4]:
# np.asarray.nonzero()
import numpy as np
 
a = np.arange(10)
 
b = np.where(a < 5, a, a * 10)
 
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [5]:
# Broadcasting with numpy.where()

import numpy as np
 
a = np.arange(12).reshape(3, 4)
 
b = np.arange(4).reshape(1, 4)
 
print(a)
print(b)
 
# Broadcasts (a < 5, a, and b * 10)
# of shape (3, 4), (3, 4) and (1, 4)
c = np.where(a < 5, a, b * 10)
 
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4 10 20 30]
 [ 0 10 20 30]]
